! generated by Norcroft Unix SPARC C 350/350/349/ [Apr 26 1991, 08:08:00]
.text
        .align 8
 .global ___sdiv10
 .global ___remainder
 .global ___divide
 .global ___udiv10
 .global ___uremainder
 .global ___udivide
 .global _rem
!
 !
!
___codeseg:
 !
!
___udivide:
 save	%sp,-0x40,%sp
 sethi	%hi(___dataseg),%g1
 or	%g1,%lo(___dataseg),%i3
 or	%i0,%g0,%i2
 subcc	%i2,0x11,%g0
 bgeu	L4F2
 sll	%i2,0x2,%i2
 sethi	%hi(L103F2),%g1
 or	%g1,%lo(L103F2),%g1
 ld	[%i2+%g1],%i2
 jmpl	%i2,%g0
 nop
L103F2:
 .word	L22F2
 .word	L21F2
 .word	L20F2
 .word	L19F2
 .word	L18F2
 .word	L17F2
 .word	L16F2
 .word	L15F2
 .word	L14F2
 .word	L13F2
 .word	L12F2
 .word	L11F2
 .word	L10F2
 .word	L9F2
 .word	L8F2
 .word	L7F2
 .word	L6F2
L22F2:
!! orcc	%g0,%g0,%i0
 st	%i1,[%i3]
 ret
 restore	%g0, %g0, %o0
L21F2:
!! orcc	%i1,%g0,%i0
 st	%g0,[%i3]
 ret
 restore	%i1,%g0,%o0
L20F2:
 andcc	%i1,0x1,%i0
 st	%i0,[%i3]
 srl	%i1,0x1,%i0
 ret
 restore
L19F2:
 srl	%i1,0x1,%i0
 srl	%i0,0x2,%i2
 addcc	%i2,%i0,%i0
 srl	%i0,0x4,%i2
 addcc	%i2,%i0,%i0
 srl	%i0,0x8,%i2
 addcc	%i2,%i0,%i0
 srl	%i0,0x10,%i2
 addcc	%i2,%i0,%i0
 srl	%i0,0x3,%i0
 srl	%i1,0x2,%i2
 add	%i2,%i0,%i0
 or	%i0,%g0,%i2
 sub	%i1,%i2,%i1
 add	%i2,%i2,%i2
 sub	%i1,%i2,%i1
 subcc	%i1,0x3,%g0
 blu	L45F2
 nop
 sub	%i1,0x3,%i1
 subcc	%i1,0x3,%g0
 blu	L45F2
 add	%i0,0x1,%i0
 sub	%i1,0x3,%i1
 ba	L45F2
 add	%i0,0x1,%i0
L18F2:
 and	%i1,0x3,%i0
 st	%i0,[%i3]
 srl	%i1,0x2,%i0
 ret
 restore
L17F2:
 srl	%i1,0x2,%i0
 sub	%i1,%i0,%i0
 srl	%i0,0x4,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x8,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x10,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x2,%i0
 or	%i0,%g0,%i2
 sub	%i1,%i2,%i1
 sll	%i2,0x2,%i2
 sub	%i1,%i2,%i1
 subcc	%i1,0x5,%g0
 blu	L45F2
 nop
 sub	%i1,0x5,%i1
 ba	L45F2
 add	%i0,0x1,%i0
L16F2:
 srl	%i1,0x1,%i0
 srl	%i0,0x2,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x4,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x8,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x10,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x2,%i0
 add	%i0,%i0,%i4
 or	%i0,%g0,%i2
 add	%i4,%i2,%i2
 add	%i2,%i2,%i2
 sub	%i1,%i2,%i1
 subcc	%i1,0x6,%g0
 blu	L45F2
 nop
 subcc	%i1,0x6,%i1
 ba	L45F2
 add	%i0,0x1,%i0
L15F2:
 srl	%i1,0x1,%i0
 srl	%i0,0x3,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x6,%i2
 add	%i2,%i0,%i0
 srl	%i0,0xc,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x18,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x2,%i0
 or	%i0,%g0,%i2
 add	%i1,%i2,%i1
 sll	%i2,0x3,%i2
 sub	%i1,%i2,%i1
 subcc	%i1,0x7,%g0
 blu	L45F2
 nop
 sub	%i1,0x7,%i1
 ba	L45F2
 add	%i0,0x1,%i0
L14F2:
 and	%i1,0x7,%i0
 st	%i0,[%i3]
 srl	%i1,0x3,%i0
 ret
 restore
L13F2:
 srl	%i1,0x3,%i0
 sub	%i1,%i0,%i0
 srl	%i0,0x6,%i2
 add	%i2,%i0,%i0
 srl	%i0,0xc,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x18,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x3,%i0
 or	%i0,%g0,%i2
 sub	%i1,%i2,%i1
 sll	%i2,0x3,%i2
 sub	%i1,%i2,%i1
 subcc	%i1,0x9,%g0
 blu	L45F2
 nop
 sub	%i1,0x9,%i1
 ba	L45F2
 add	%i0,0x1,%i0
L12F2:
 srl	%i1,0x2,%i0
 sub	%i1,%i0,%i0
 srl	%i0,0x4,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x8,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x10,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x3,%i0
 sll	%i0,0x2,%i4
 or	%i0,%g0,%i2
 add	%i4,%i2,%i2
 add	%i2,%i2,%i2
 sub	%i1,%i2,%i1
 subcc	%i1,0xa,%g0
 blu	L45F2
 nop
 sub	%i1,0xa,%i1
 ba	L45F2
 add	%i0,0x1,%i0
L11F2:
 srl	%i1,0x3,%i0
 srl	%i1,0x5,%i2
 sub	%i1,%i0,%i0
 add	%i2,%i0,%i0
 srl	%i1,0x9,%i2
 add	%i2,%i0,%i0
 srl	%i0,0xa,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x14,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x2,%i0
 srl	%i1,0x1,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x3,%i0
 add	%i0,%i0,%i4
 or	%i0,%g0,%i2
 add	%i1,%i2,%i1
 add	%i4,%i2,%i4
 sll	%i4,0x2,%i2
 sub	%i1,%i2,%i1
 subcc	%i1,0xb,%g0
 blu	L45F2
 nop
 sub	%i1,0xb,%i1
 ba	L45F2
 add	%i0,0x1,%i0
L10F2:
 srl	%i1,0x1,%i0
 srl	%i0,0x2,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x4,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x8,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x10,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x3,%i0
 add	%i0,%i0,%i4
 or	%i0,%g0,%i2
 add	%i4,%i2,%i2
 sll	%i2,0x2,%i2
 sub	%i1,%i2,%i1
 subcc	%i1,0xc,%g0
 blu	L45F2
 nop
 sub	%i1,0xc,%i1
 ba	L45F2
 add	%i0,0x1,%i0
L9F2:
 srl	%i1,0x4,%i0
 srl	%i1,0x6,%i2
 sub	%i1,%i0,%i0
 sub	%i0,%i2,%i0
 srl	%i1,0xa,%i2
 add	%i2,%i0,%i0
 srl	%i0,0xc,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x18,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x3,%i0
 srl	%i1,0x1,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x3,%i0
 add	%i0,%i0,%i4
 or	%i0,%g0,%i2
 sub	%i1,%i2,%i1
 add	%i4,%i2,%i4
 sll	%i4,0x2,%i2
 sub	%i1,%i2,%i1
 subcc	%i1,0xd,%g0
 blu	L45F2
 nop
 sub	%i1,0xd,%i1
 ba	L45F2
 add	%i0,0x1,%i0
L8F2:
 srl	%i1,0x1,%i0
 srl	%i0,0x3,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x6,%i2
 add	%i2,%i0,%i0
 srl	%i0,0xc,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x18,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x3,%i0
 sll	%i0,0x3,%i4
 or	%i0,%g0,%i2
 sub	%i4,%i2,%i2
 add	%i2,%i2,%i2
 sub	%i1,%i2,%i1
 subcc	%i1,0xe,%g0
 blu	L45F2
 nop
 sub	%i1,0xe,%i1
 ba	L45F2
 add	%i0,0x1,%i0
L7F2:
 srl	%i1,0x1,%i0
 srl	%i0,0x4,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x8,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x10,%i2
 add	%i2,%i0,%i0
 srl	%i0,0x3,%i0
 or	%i0,%g0,%i2
 add	%i1,%i2,%i1
 sll	%i2,0x4,%i2
 sub	%i1,%i2,%i1
 subcc	%i1,0xf,%g0
 blu	L45F2
 nop
 sub	%i1,0xf,%i1
 add	%i0,0x1,%i0
L45F2:
 st	%i1,[%i3]
 ret
 restore
L6F2:
 and	%i1,0xf,%i0
 st	%i0,[%i3]
 srl	%i1,0x4,%i0
 ret
 restore
L4F2:
 or	%g0,%g0,%i4
 sethi	0x200000,%i5
 sethi	0x200000,%g1
 subcc	%i1,%g1,%g0
 bgeu	L49F2
 or	%i0,%g0,%i2
 or	%i1,%g0,%i5
L49F2:
 subcc	%i5,%i2,%g0
 bleu	L52F2
 nop
 add	%i2,%i2,%g2
 subcc	%g2,%i5,%g0
 bgeu	L56F2
 nop
 sll	%i2,0x2,%g2
 subcc	%g2,%i5,%g0
 bgeu	L60F2
 nop
 sll	%i2,0x3,%g2
 subcc	%g2,%i5,%g0
 bgeu	L64F2
 nop
 sll	%i2,0x4,%g2
 subcc	%g2,%i5,%g0
 bgeu	L68F2
 nop
 sll	%i2,0x5,%g2
 subcc	%g2,%i5,%g0
 bgeu	L72F2
 nop
 sll	%i2,0x6,%g2
 subcc	%g2,%i5,%g0
 bgeu	L76F2
 nop
 sll	%i2,0x7,%g2
 subcc	%g2,%i5,%g0
 bgeu	L80F2
 nop
 ba	L49F2
 sll	%i2,0x8,%i2
L80F2:
 sll	%i2,0x7,%i5
 subcc	%i5,%i1,%g0
 bgu	L81F2
 nop
 add	%i4,0x1,%i4
 sub	%i1,%i5,%i1
L81F2:
 add	%i4,%i4,%i4
L76F2:
 sll	%i2,0x6,%i5
 subcc	%i5,%i1,%g0
 bgu	L83F2
 nop
 add	%i4,0x1,%i4
 sub	%i1,%i5,%i1
L83F2:
 addcc	%i4,%i4,%i4
L72F2:
 sll	%i2,0x5,%i5
 subcc	%i5,%i1,%g0
 bgu	L85F2
 nop
 add	%i4,0x1,%i4
 sub	%i1,%i5,%i1
L85F2:
 add	%i4,%i4,%i4
L68F2:
 sll	%i2,0x4,%i5
 subcc	%i5,%i1,%g0
 bgu	L87F2
 nop
 add	%i4,0x1,%i4
 sub	%i1,%i5,%i1
L87F2:
 add	%i4,%i4,%i4
L64F2:
 sll	%i2,0x3,%i5
 subcc	%i5,%i1,%g0
 bgu	L89F2
 nop
 add	%i4,0x1,%i4
 sub	%i1,%i5,%i1
L89F2:
 add	%i4,%i4,%i4
L60F2:
 sll	%i2,0x2,%i5
 subcc	%i5,%i1,%g0
 bgu	L91F2
 nop
 add	%i4,0x1,%i4
 sub	%i1,%i5,%i1
L91F2:
 add	%i4,%i4,%i4
L56F2:
 add	%i2,%i2,%i5
 subcc	%i5,%i1,%g0
 bgu	L93F2
 nop
 add	%i4,0x1,%i4
 sub	%i1,%i5,%i1
L93F2:
 add	%i4,%i4,%i4
L52F2:
 subcc	%i1,%i2,%g0
 blu	L95F2
 nop
 add	%i4,0x1,%i4
 sub	%i1,%i2,%i1
L95F2:
 srl	%i2,0x1,%i5
 subcc	%i5,%i0,%g0
 blu	L97F2
 nop
 add	%i4,%i4,%i4
 ba	L80F2
 srl	%i2,0x8,%i2
L97F2:
!! orcc	%i4,%g0,%i0
 st	%i1,[%i3]
 ret
 restore %i4,%g0,%o0
 !
!
___uremainder:
 save	%sp,-0x40,%sp
 or	%i0,%g0,%o0
 call	___udivide
 or	%i1,%g0,%o1
 sethi	%hi(___dataseg),%g1
 ld	[%g1+%lo(___dataseg)],%i0
 ret
 restore
 !
!
___udiv10:
 or	%o0,%g0,%o1
 srl	%o0,0x1,%o0
 srl	%o0,0x1,%o2
 add	%o2,%o0,%o0
 srl	%o0,0x4,%o2
 add	%o2,%o0,%o0
 srl	%o0,0x8,%o2
 add	%o2,%o0,%o0
 srl	%o0,0x10,%o2
 add	%o2,%o0,%o0
 srl	%o0,0x3,%o0
 sll	%o0,0x2,%o2
 add	%o2,%o0,%o2
 add	%o2,%o2,%o2
 sub	%o1,%o2,%o1
 subcc	%o1,0xa,%g0
 blu	L4F4
 nop
 sub	%o1,0xa,%o1
 add	%o0,0x1,%o0
L4F4:
 sethi	%hi(___dataseg),%g1
 retl
 st	%o1,[%g1+%lo(___dataseg)]
 !
!
___divide:
 save	%sp,-0x40,%sp
 sethi	0x200000,%g1
 xor	%i0,%i1,%i3
 srl	%i3,0x1,%i3
 and	%i1,%g1,%i2
 subcc	%i1,%g0,%g0
 bge	L4F5
 or	%i2,%i3,%i2
 sub	%g0,%i1,%i1
L4F5:
 subcc	%i0,%g0,%g0
 bge	L6F5
 nop
 sub	%g0,%i0,%i0
L6F5:
 sethi	%hi(___dataseg),%g1
 or	%g1,%lo(___dataseg),%i4
 or	%i0,%g0,%i3
 subcc	%i3,0x11,%g0
 bgeu	L8F5
 sll	%i3,0x2,%i3
 sethi	%hi(L175F5),%g1
 or	%g1,%lo(L175F5),%g1
 ld	[%i3+%g1],%i3
 jmpl	%i3,%g0
 nop
L175F5:
 .word	L26F5
 .word	L25F5
 .word	L24F5
 .word	L23F5
 .word	L22F5
 .word	L21F5
 .word	L20F5
 .word	L19F5
 .word	L18F5
 .word	L17F5
 .word	L16F5
 .word	L15F5
 .word	L14F5
 .word	L13F5
 .word	L12F5
 .word	L11F5
 .word	L10F5
L26F5:
 subcc	%i2,%g0,%g0
 bge	L27F5
 nop
 sub	%g0,%i1,%i0
 ba	L29F5
 st	%i0,[%i4]
L27F5:
 st	%i1,[%i4]
L29F5:
 ret
 restore	%g0,%g0,%o0
L25F5:
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i0
 be	L30F5
 st	%g0,[%i4]
 ba	L32F5
 sub	%g0,%i1,%i1
L30F5:
 sethi	0x200000,%g1
 sub	%i1,%g1,%g0
L32F5:
 ret
 restore	%i1,%g0,%o0
L24F5:
 srl	%i1,0x1,%i0
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i3
 be	L35F5
 and	%i1,0x1,%i1
 sub	%g0,%i0,%i0
L35F5:
 subcc	%i2,%g0,%g0
 bge	L115F5
 nop
L38F5:
 ba	L115F5
 sub	%g0,%i1,%i1
L23F5:
 srl	%i1,0x2,%i3
 add	%i3,%i1,%i0
 srl	%i0,0x4,%i5
 add	%i5,%i0,%i0
 srl	%i0,0x8,%i5
 add	%i5,%i0,%i0
 srl	%i0,0x10,%i5
 add	%i5,%i0,%i0
 srl	%i0,0x4,%i0
 add	%i3,%i0,%i0
 or	%i0,%g0,%i3
 sub	%i1,%i3,%i1
 add	%i3,%i3,%i3
 sub	%i1,%i3,%i1
 subcc	%i1,0x3,%g0
 bl	L39F5
 nop
 sub	%i1,0x3,%i1
 add	%i0,0x1,%i0
L39F5:
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i3
 be	L41F5
 nop
 sub	%g0,%i0,%i0
L41F5:
 subcc	%i2,%g0,%g0
 bl	L38F5
 nop
 ba	L115F5a
 st	%i1,[%i4]

L22F5:
 srl	%i1,0x2,%i0
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i3
 be	L45F5
 and	%i1,0x3,%i1
 sub	%g0,%i0,%i0
L45F5:
 subcc	%i2,%g0,%g0
 bl	L38F5
 nop
 ba	L115F5a
 st	%i1,[%i4]
L21F5:
 srl	%i1,0x1,%i0
 add	%i0,%i1,%i0
 srl	%i0,0x4,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x8,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x10,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x3,%i0
 or	%i0,%g0,%i3
 sub	%i1,%i3,%i1
 sll	%i3,0x2,%i3
 sub	%i1,%i3,%i1
 subcc	%i1,0x5,%g0
 bl	L49F5
 nop
 sub	%i1,0x5,%i1
 add	%i0,0x1,%i0
L49F5:
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i3
 be	L51F5
 nop
 sub	%g0,%i0,%i0
L51F5:
 subcc	%i2,%g0,%g0
 bl	L38F5
 nop
 ba	L115F5a
 st	%i1,[%i4]
L20F5:
 srl	%i1,0x2,%i0
 add	%i0,%i1,%i0
 srl	%i0,0x4,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x8,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x10,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x3,%i0
 add	%i0,%i0,%i5
 or	%i0,%g0,%i3
 add	%i5,%i3,%i3
 add	%i3,%i3,%i3
 sub	%i1,%i3,%i1
 subcc	%i1,0x6,%g0
 bl	L55F5
 nop
 sub	%i1,0x6,%i1
 add	%i0,0x1,%i0
L55F5:
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i3
 be	L57F5
 nop
 sub	%g0,%i0,%i0
L57F5:
 subcc	%i2,%g0,%g0
 bl	L38F5
 nop
 ba	L115F5a
 st	%i1,[%i4]
L19F5:
 srl	%i1,0x3,%i0
 add	%i0,%i1,%i0
 srl	%i0,0x6,%i3
 add	%i3,%i0,%i0
 srl	%i0,0xc,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x18,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x3,%i0
 or	%i0,%g0,%i3
 add	%i1,%i3,%i1
 sll	%i3,0x3,%i3
 sub	%i1,%i3,%i1
 subcc	%i1,0x7,%g0
 bl	L61F5
 nop
 sub	%i1,0x7,%i1
 add	%i0,0x1,%i0
L61F5:
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i3
 be	L63F5
 nop
 sub	%g0,%i0,%i0
L63F5:
 subcc	%i2,%g0,%g0
 bl	L38F5
 nop
 ba	L115F5a
 st	%i1,[%i4]
L18F5:
 srl	%i1,0x3,%i0
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i3
 be	L67F5
 and	%i1,0x7,%i1
 sub	%g0,%i0,%i0
L67F5:
 subcc	%i2,%g0,%g0
 bl	L38F5
 nop
 ba	L115F5a
 st	%i1,[%i4]
L17F5:
 srl	%i1,0x3,%i0
 sub	%i1,%i0,%i0
 srl	%i0,0x6,%i3
 add	%i3,%i0,%i0
 srl	%i0,0xc,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x18,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x3,%i0
 or	%i0,%g0,%i3
 sub	%i1,%i3,%i1
 sll	%i3,0x3,%i3
 sub	%i1,%i3,%i1
 subcc	%i1,0x9,%g0
 bl	L71F5
 nop
 sub	%i1,0x9,%i1
 add	%i0,0x1,%i0
L71F5:
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i3
 be	L73F5
 nop
 sub	%g0,%i0,%i0
L73F5:
 subcc	%i2,%g0,%g0
 bl	L38F5
 nop
 ba	L115F5a
 st	%i1,[%i4]
L16F5:
 srl	%i1,0x1,%i0
 add	%i0,%i1,%i0
 srl	%i0,0x4,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x8,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x10,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x4,%i0
 sll	%i0,0x2,%i5
 or	%i0,%g0,%i3
 add	%i5,%i3,%i3
 add	%i3,%i3,%i3
 sub	%i1,%i3,%i1
 subcc	%i1,0xa,%g0
 bl	L77F5
 nop
 sub	%i1,0xa,%i1
 add	%i0,0x1,%i0
L77F5:
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i3
 be	L79F5
 nop
 sub	%g0,%i0,%i0
L79F5:
 subcc	%i2,%g0,%g0
 bl	L38F5
 nop
 ba	L115F5a
 st	%i1,[%i4]
L15F5:
 srl	%i1,0x3,%i0
 srl	%i1,0x5,%i3
 sub	%i1,%i0,%i0
 add	%i3,%i0,%i0
 srl	%i1,0x9,%i3
 add	%i3,%i0,%i0
 srl	%i0,0xa,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x14,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x2,%i0
 srl	%i1,0x1,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x3,%i0
 add	%i0,%i0,%i5
 or	%i0,%g0,%i3
 add	%i1,%i3,%i1
 add	%i5,%i3,%i5
 sll	%i5,0x2,%i3
 sub	%i1,%i3,%i1
 subcc	%i1,0xb,%g0
 bl	L83F5
 nop
 sub	%i1,0xb,%i1
 add	%i0,0x1,%i0
L83F5:
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i3
 be	L85F5
 nop
 sub	%g0,%i0,%i0
L85F5:
 subcc	%i2,%g0,%g0
 bl	L38F5
 nop
 ba	L115F5a
 st	%i1,[%i4]
L14F5:
 srl	%i1,0x1,%i0
 srl	%i0,0x2,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x4,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x8,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x10,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x3,%i0
 add	%i0,%i0,%i5
 or	%i0,%g0,%i3
 add	%i5,%i3,%i3
 sll	%i3,0x2,%i3
 sub	%i1,%i3,%i1
 subcc	%i1,0xc,%g0
 bl	L89F5
 nop
 sub	%i1,0xc,%i1
 add	%i0,0x1,%i0
L89F5:
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i3
 be	L91F5
 nop
 sub	%g0,%i0,%i0
L91F5:
 subcc	%i2,%g0,%g0
 bl	L38F5
 nop
 ba	L115F5a
 st	%i1,[%i4]
L13F5:
 srl	%i1,0x4,%i0
 srl	%i1,0x6,%i3
 sub	%i1,%i0,%i0
 sub	%i0,%i3,%i0
 srl	%i1,0xa,%i3
 add	%i3,%i0,%i0
 srl	%i0,0xc,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x18,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x3,%i0
 srl	%i1,0x1,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x3,%i0
 add	%i0,%i0,%i5
 or	%i0,%g0,%i3
 sub	%i1,%i3,%i1
 add	%i5,%i3,%i5
 sll	%i5,0x2,%i3
 sub	%i1,%i3,%i1
 subcc	%i1,0xd,%g0
 bl	L95F5
 nop
 sub	%i1,0xd,%i1
 add	%i0,0x1,%i0
L95F5:
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i3
 be	L97F5
 nop
 sub	%g0,%i0,%i0
L97F5:
 subcc	%i2,%g0,%g0
 bl	L38F5
 nop
 ba	L115F5a
 st	%i1,[%i4]
L12F5:
 srl	%i1,0x1,%i0
 srl	%i0,0x3,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x6,%i3
 add	%i3,%i0,%i0
 srl	%i0,0xc,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x18,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x3,%i0
 sll	%i0,0x3,%i5
 or	%i0,%g0,%i3
 sub	%i5,%i3,%i3
 add	%i3,%i3,%i3
 sub	%i1,%i3,%i1
 subcc	%i1,0xe,%g0
 bl	L101F5
 nop
 sub	%i1,0xe,%i1
 add	%i0,0x1,%i0
L101F5:
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i3
 be	L103F5
 nop
 sub	%g0,%i0,%i0
L103F5:
 subcc	%i2,%g0,%g0
 bl	L38F5
 nop
 ba	L115F5a
 st	%i1,[%i4]
L11F5:
 srl	%i1,0x1,%i0
 srl	%i0,0x4,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x8,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x10,%i3
 add	%i3,%i0,%i0
 srl	%i0,0x3,%i0
 or	%i0,%g0,%i3
 add	%i1,%i3,%i1
 sll	%i3,0x4,%i3
 sub	%i1,%i3,%i1
 subcc	%i1,0xf,%g0
 bl	L107F5
 nop
 sub	%i1,0xf,%i1
 add	%i0,0x1,%i0
L107F5:
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i3
 be	L109F5
 nop
 sub	%g0,%i0,%i0
L109F5:
 subcc	%i2,%g0,%g0
 bl	L38F5
 nop
 ba	L115F5a
 st	%i1,[%i4]
L10F5:
 srl	%i1,0x4,%i0
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i3
 be	L113F5
 and	%i1,0xf,%i1
 sub	%g0,%i0,%i0
L113F5:
 subcc	%i2,%g0,%g0
 bl	L38F5
 nop
L115F5:
 st	%i1,[%i4]
L115F5a:
 ret
 restore
L8F5:
 or	%g0,%g0,%i5
 or	%i0,%g0,%i3
L117F5:
 subcc	%i1,%i3,%g0
 bleu	L120F5
 nop
 add	%i3,%i3,%g2
 subcc	%g2,%i1,%g0
 bgeu	L124F5
 nop
 sll	%i3,0x2,%g2
 subcc	%g2,%i1,%g0
 bgeu	L128F5
 nop
 sll	%i3,0x3,%g2
 subcc	%g2,%i1,%g0
 bgeu	L132F5
 nop
 sll	%i3,0x4,%g2
 subcc	%g2,%i1,%g0
 bgeu	L136F5
 nop
 sll	%i3,0x5,%g2
 subcc	%g2,%i1,%g0
 bgeu	L140F5
 nop
 sll	%i3,0x6,%g2
 subcc	%g2,%i1,%g0
 bgeu	L144F5
 nop
 sll	%i3,0x7,%g2
 subcc	%g2,%i1,%g0
 bgeu	L148F5
 nop
 ba	L117F5
 sll	%i3,0x8,%i3
L148F5:
 sll	%i3,0x7,%g2
 subcc	%g2,%i1,%g0
 bgu	L149F5
 nop
 addcc	%i5,0x1,%i5
 sub	%i1,%g2,%i1
L149F5:
 add	%i5,%i5,%i5
L144F5:
 sll	%i3,0x6,%g2
 subcc	%g2,%i1,%g0
 bgu	L151F5
 nop
 add	%i5,0x1,%i5
 sub	%i1,%g2,%i1
L151F5:
 add	%i5,%i5,%i5
L140F5:
 sll	%i3,0x5,%g2
 subcc	%g2,%i1,%g0
 bgu	L153F5
 nop
 add	%i5,0x1,%i5
 sub	%i1,%g2,%i1
L153F5:
 add	%i5,%i5,%i5
L136F5:
 sll	%i3,0x4,%g2
 subcc	%g2,%i1,%g0
 bgu	L155F5
 nop
 add	%i5,0x1,%i5
 sub	%i1,%g2,%i1
L155F5:
 add	%i5,%i5,%i5
L132F5:
 sll	%i3,0x3,%g2
 subcc	%g2,%i1,%g0
 bgu	L157F5
 nop
 add	%i5,0x1,%i5
 sub	%i1,%g2,%i1
L157F5:
 add	%i5,%i5,%i5
L128F5:
 sll	%i3,0x2,%g2
 subcc	%g2,%i1,%g0
 bgu	L159F5
 nop
 add	%i5,0x1,%i5
 sub	%i1,%g2,%i1
L159F5:
 add	%i5,%i5,%i5
L124F5:
 add	%i3,%i3,%g2
 subcc	%g2,%i1,%g0
 bgu	L161F5
 nop
 add	%i5,0x1,%i5
 sub	%i1,%g2,%i1
L161F5:
 add	%i5,%i5,%i5
L120F5:
 subcc	%i1,%i3,%g0
 blu	L163F5
 nop
 add	%i5,0x1,%i5
 sub	%i1,%i3,%i1
L163F5:
 srl	%i3,0x1,%g2
 subcc	%g2,%i0,%g0
 blu	L165F5
 nop
 add	%i5,%i5,%i5
 ba	L148F5
 srl	%i3,0x8,%i3
L165F5:
 sethi	0x100000,%g1
 andcc	%i2,%g1,%i0
 be	L167F5
 nop
 sub	%g0,%i5,%i5
L167F5:
 subcc	%i2,%g0,%g0
 bge	L169F5
 nop
 sub	%g0,%i1,%i1
L169F5:
!! orcc	%i5,%g0,%i0
 st	%i1,[%i4]
 ret
 restore %i5,%g0,%o0
 !
!
___remainder:
 save	%sp,-0x40,%sp
 orcc	%i0,%g0,%o0
 call	___divide
 or	%i1,%g0,%o1
 sethi	%hi(___dataseg),%g1
 ld	[%g1+%lo(___dataseg)],%i0
 ret
 restore
 !
!
___sdiv10:
 orcc	%o0,%g0,%o2
 bge	L4F7
 nop
 subcc	%g0,%o0,%o0
L4F7:
 or	%o0,%g0,%o1
 srl	%o0,0x1,%o0
 sra	%o0,0x1,%o3
 add	%o3,%o0,%o0
 sra	%o0,0x4,%o3
 add	%o3,%o0,%o0
 sra	%o0,0x8,%o3
 add	%o3,%o0,%o0
 sra	%o0,0x10,%o3
 add	%o3,%o0,%o0
 sra	%o0,0x3,%o0
 sll	%o0,0x2,%o3
 add	%o3,%o0,%o3
 add	%o3,%o3,%o3
 sub	%o1,%o3,%o1
 subcc	%o1,0xa,%g0
 bl	L6F7
 nop
 sub	%o1,0xa,%o1
 add	%o0,0x1,%o0
L6F7:
 subcc	%o2,%g0,%g0
 bge	L8F7
 nop
 sub	%g0,%o1,%o1
 sub	%g0,%o0,%o0
L8F7:
 sethi	%hi(___dataseg),%g1
 retl
 st	%o1,[%g1+%lo(___dataseg)]
 !
 .data
        .align 8
!
___dataseg:
_rem:
 .word	0x00000000
 .word	0x00000000
!
!
!
!
! END
